spring:
  application:
    name: citi_aid_backend
  data:
    mongodb:
      uri: mongodb://mongo:PqPwuufLGIVTZvXAWiANMNcgsNsZkraf@centerbeam.proxy.rlwy.net:39499/citi_aid?authSource=admin
#      mongodb+srv://citi_aid:yojitSiddhant@citi-aid.j6pmitp.mongodb.net/citi_aid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  image:
    storage:
      path: target/images

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs     # default: /v3/api-docs
  swagger-ui:
    path: /swagger-ui   # default: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    try-it-out-enabled: true
    filter: true
  cors:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.mongodb.driver: WARN
